REGION=us-east-1
ECR_REPOSITORY=397823652972.dkr.ecr.us-east-1.amazonaws.com
GENERIC_CD_JOB=K8S_DEPLOYMENT
DEPLOYMENT_TYPE=K8S_ROLLING_UPDATE
SERVICE_FILE_PATH=k8s/service.yml
DEPLOYMENT_FILE_PATH=k8s/deployment.yml